In [2]:
import os
import sys
import librosa
import tflearn
import tensorflow as tf
import librosa.display
import IPython.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.style as ms
%matplotlib inline

curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Instructions for updating:
Colocations handled automatically by placer.


In [3]:
os.chdir('C:/Users/karti/Speech/LibriSpeech/dev-clean/')

In [4]:
new_y=[]
f = open("y.txt", "r")
for x in f:
  new_y.append(int(x.strip()))

In [5]:
len(new_y)

2703

In [6]:
new_y = np.array(new_y).reshape(-1,1)

In [7]:
# import pickle
# with open('mfccs.pkl', 'wb') as f:
#     pickle.dump(mfccs, f)

In [8]:
# from sklearn import preprocessing
# le = preprocessing.LabelEncoder()
# le.fit(new_y)
# res=le.transform(new_y)

In [9]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(new_y)
res=enc.transform(new_y).toarray()

In [10]:
res[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [11]:
import pickle
new_mfccs=[]
with open('mfccs.pkl', 'rb') as f:
    new_mfccs = pickle.load(f)

In [12]:
len(new_mfccs)

2703

In [13]:
uni=[]
for i in new_y:
    if(i not in uni):
        uni.append(i)

In [14]:
len(uni)

40

In [15]:
print((new_mfccs[0][0]).mean())

-320.3857


In [16]:
len(new_mfccs)

2703

In [17]:
new_mfccs[200]

array([[-422.61273   , -420.83978   , -421.63156   , ..., -474.38013   ,
        -474.8237    , -455.48975   ],
       [  47.226917  ,   46.655884  ,   49.06836   , ...,   48.494804  ,
          46.773216  ,   48.03399   ],
       [ -28.221333  ,  -29.218151  ,  -22.760973  , ...,    9.897391  ,
           8.224331  ,  -11.62133   ],
       ...,
       [  -6.1200995 ,   -6.310774  ,   -4.5463758 , ...,   -6.9940376 ,
          -5.34544   ,    3.0775084 ],
       [  10.111799  ,   13.743115  ,   21.587517  , ...,    0.93357164,
          -2.2579224 ,   -6.3719716 ],
       [   3.061989  ,    9.477272  ,   14.413259  , ...,   11.6231785 ,
           6.7680616 ,    5.625402  ]], dtype=float32)

In [18]:
padding_gaussian_mfccs=[]

In [19]:
len(new_mfccs[50][0])

464

In [20]:
# find max
min_len=len(new_mfccs[0][0])
t=0
for i in new_mfccs:
    t+=1
    if(len(i[0])<min_len):
        min_len=len(i[0])
print(min_len)

63


In [21]:
# find max
max_len=0
t=0
for i in new_mfccs:
    t+=1
    if(len(i[0])>max_len):
        max_len=len(i[0])
print(max_len)

1406


In [22]:
mid=(min_len+max_len)//2
mid

734

In [23]:
for i in range(len(new_mfccs)):
    fill=[]
    for j in range (len(new_mfccs[i])):
        inner_fill=[]
        loop=min(len(new_mfccs[i][j]), mid);
        for k in range(loop):
            inner_fill.append(new_mfccs[i][j][k])
        pad_gaussian=np.random.normal(np.mean(new_mfccs[i][j]), np.std(new_mfccs[i][j]), mid-loop)
        for k in pad_gaussian:
            inner_fill.append(k)
        fill.append(inner_fill)
#     print(fill)
    padding_gaussian_mfccs.append(fill)
#     print(len(padding0_mfccs[0][0]))
#     break

In [24]:
(padding_gaussian_mfccs[1000][0])

[-450.63278,
 -455.9079,
 -468.2771,
 -483.4269,
 -504.55322,
 -520.7981,
 -531.58325,
 -529.26465,
 -529.60345,
 -529.4596,
 -530.53015,
 -533.12445,
 -533.6824,
 -445.3553,
 -306.8135,
 -205.34357,
 -153.17136,
 -115.54723,
 -104.79059,
 -117.03351,
 -181.2685,
 -275.233,
 -285.45474,
 -266.15402,
 -259.69415,
 -268.7397,
 -296.56635,
 -280.64496,
 -259.26343,
 -257.8872,
 -262.8381,
 -287.89334,
 -312.0161,
 -326.1717,
 -330.1987,
 -319.77155,
 -221.61385,
 -142.40068,
 -117.90954,
 -144.18246,
 -146.3956,
 -131.96016,
 -154.01106,
 -190.37517,
 -288.1971,
 -386.11334,
 -295.431,
 -283.95782,
 -359.58337,
 -437.8038,
 -353.6401,
 -283.6637,
 -248.09918,
 -232.39243,
 -244.92078,
 -289.73557,
 -355.93192,
 -369.45676,
 -283.08267,
 -204.83278,
 -189.94092,
 -207.0813,
 -233.50075,
 -291.1629,
 -371.80136,
 -423.10516,
 -395.412,
 -361.64755,
 -337.19696,
 -326.59537,
 -324.70407,
 -295.72998,
 -218.96959,
 -188.85019,
 -188.88844,
 -211.25433,
 -256.4105,
 -271.3039,
 -251.9944,
 -23

In [25]:
# import pickle
# with open('padding_gauss_mfccs_lstm.pkl', 'wb') as f:
#     pickle.dump(padding_gaussian_mfccs, f)

In [26]:
res

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(padding_gaussian_mfccs, res, test_size=0.33, random_state=42)

In [28]:
import numpy as np
# import tensorflow as tf
# from tensorflow import keras
# from tensorflow.keras import layers

In [29]:
X_train=np.array(X_train)
X_train.shape

(1811, 13, 734)

In [30]:
X_test=np.transpose(X_test,(0,2,1))

In [31]:
X_test.shape

(892, 734, 13)

In [32]:
X_train=np.transpose(X_train,(0,2,1))

In [33]:
X_train.shape

(1811, 734, 13)

# Model_2

In [34]:
net_lstm = tflearn.input_data([None, 734, 13])
# net = tflearn.embedding(net, input_dim=10000, output_dim=128)
net_lstm = tflearn.lstm(net_lstm, 32, dropout=0.8, return_seq= False)
# net_lstm = tflearn.lstm(net_lstm, 128, dropout=0.4)
net_lstm = tflearn.fully_connected(net_lstm,40, activation='softmax')
net_lstm = tflearn.regression(net_lstm, optimizer='adam', learning_rate=0.001,
                         loss='categorical_crossentropy')

# Training

Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [35]:
model2_lstm = tflearn.DNN(net_lstm, tensorboard_verbose=0)

Instructions for updating:
Use tf.cast instead.


In [35]:
model2_lstm.fit(X_train, y_train, n_epoch=1000, show_metric=True, batch_size=128,snapshot_step=100)

Training Step: 14999  | total loss: 0.97220 | time: 9.500s
| Adam | epoch: 1000 | loss: 0.97220 - acc: 0.8431 -- iter: 1792/1811
Training Step: 15000  | total loss: 0.90553 | time: 10.250s
| Adam | epoch: 1000 | loss: 0.90553 - acc: 0.8478 -- iter: 1811/1811
--


In [41]:
model2_lstm.fit(X_train, y_train, n_epoch=100, show_metric=True, batch_size=128,snapshot_step=100)

Training Step: 17999  | total loss: 0.72980 | time: 8.520s
| Adam | epoch: 100 | loss: 0.72980 - acc: 0.8737 -- iter: 1792/1811
Training Step: 18000  | total loss: 0.70208 | time: 9.160s
| Adam | epoch: 100 | loss: 0.70208 - acc: 0.8738 -- iter: 1811/1811
--


In [47]:
y_pred = model2_lstm.predict(X_train)

In [48]:
np.sum(np.argmax(y_train, axis=1)==np.argmax(y_pred, axis=1))/len(y_train)

0.713970182219768

In [49]:
y_pred = model2_lstm.predict(X_test)

In [50]:
np.sum(np.argmax(y_test, axis=1)==np.argmax(y_pred, axis=1))/len(y_test)

0.6961883408071748

In [46]:
model2_lstm.save('model2_gauss_mfccs_lstm_32.tflearn')

INFO:tensorflow:C:\Users\karti\Speech\LibriSpeech\dev-clean\model2_gauss_mfccs_lstm_32.tflearn is not in all_model_checkpoint_paths. Manually adding it.


In [46]:
model2_lstm.load('model2_gauss_mfccs_lstm_32.tflearn')

INFO:tensorflow:Restoring parameters from C:\Users\karti\Speech\LibriSpeech\dev-clean\model2_gauss_mfccs_lstm_32.tflearn


# Model_3

In [34]:
net_lstm_3 = tflearn.input_data([None, 734, 13])
# net = tflearn.embedding(net, input_dim=10000, output_dim=128)
net_lstm_3 = tflearn.lstm(net_lstm_3, 32, dropout=0.8, return_seq= False)
# net_lstm = tflearn.lstm(net_lstm, 128, dropout=0.4)
net_lstm_3 = tflearn.fully_connected(net_lstm_3,40, activation='softmax')
net_lstm_3 = tflearn.regression(net_lstm_3, optimizer='adam', learning_rate=0.001,
                         loss='categorical_crossentropy')

# Training

Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [35]:
model3_lstm = tflearn.DNN(net_lstm_3, tensorboard_verbose=0)

Instructions for updating:
Use tf.cast instead.


In [36]:
model3_lstm.fit(X_train, y_train, n_epoch=1000, show_metric=True, batch_size=128,snapshot_step=100)

Training Step: 14999  | total loss: 0.95084 | time: 8.691s
| Adam | epoch: 1000 | loss: 0.95084 - acc: 0.8521 -- iter: 1792/1811
Training Step: 15000  | total loss: 0.89566 | time: 9.369s
| Adam | epoch: 1000 | loss: 0.89566 - acc: 0.8568 -- iter: 1811/1811
--


In [49]:
model3_lstm.fit(X_train, y_train, n_epoch=100, show_metric=True, batch_size=128,snapshot_step=100)

Training Step: 17999  | total loss: 0.68681 | time: 13.624s
| Adam | epoch: 1200 | loss: 0.68681 - acc: 0.8831 -- iter: 1792/1811
Training Step: 18000  | total loss: 0.64160 | time: 14.700s
| Adam | epoch: 1200 | loss: 0.64160 - acc: 0.8893 -- iter: 1811/1811
--


In [56]:
y_pred = model3_lstm.predict(X_train)

In [57]:
np.sum(np.argmax(y_train, axis=1)==np.argmax(y_pred, axis=1))/len(y_train)

0.6123688569850911

In [58]:
y_pred = model3_lstm.predict(X_test)

In [59]:
np.sum(np.argmax(y_test, axis=1)==np.argmax(y_pred, axis=1))/len(y_test)

0.5717488789237668

In [54]:
model3_lstm.save('model3_gauss_mfccs_lstm_128.tflearn')

INFO:tensorflow:C:\Users\karti\Speech\LibriSpeech\dev-clean\model3_gauss_mfccs_lstm_128.tflearn is not in all_model_checkpoint_paths. Manually adding it.


In [55]:
model3_lstm.load('model3_gauss_mfccs_lstm_128.tflearn')

INFO:tensorflow:Restoring parameters from C:\Users\karti\Speech\LibriSpeech\dev-clean\model3_gauss_mfccs_lstm_128.tflearn


In [40]:
net_lstm = tflearn.input_data([None, 734, 13])
# net = tflearn.embedding(net, input_dim=10000, output_dim=128)
net_lstm = tflearn.lstm(net_lstm, 64, dropout=0.8, return_seq= False)
# net_lstm = tflearn.lstm(net_lstm, 128, dropout=0.4)
net_lstm = tflearn.fully_connected(net_lstm,40, activation='softmax')
net_lstm = tflearn.regression(net_lstm, optimizer='adam', learning_rate=0.001,
                         loss='categorical_crossentropy')

# Training

Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [41]:
model_lstm = tflearn.DNN(net_lstm, tensorboard_verbose=0)

Instructions for updating:
Use tf.cast instead.


In [42]:
model_lstm.fit(X_train, y_train, n_epoch=1000, show_metric=True, batch_size=128,snapshot_step=100)

Training Step: 14999  | total loss: 0.85231 | time: 21.043s
| Adam | epoch: 1000 | loss: 0.85231 - acc: 0.9179 -- iter: 1792/1811
Training Step: 15000  | total loss: 0.77681 | time: 22.698s
| Adam | epoch: 1000 | loss: 0.77681 - acc: 0.9245 -- iter: 1811/1811
--


In [54]:
model_lstm.fit(X_train, y_train, n_epoch=100, show_metric=True, batch_size=128,snapshot_step=100)

Training Step: 17999  | total loss: 0.17194 | time: 26.991s
| Adam | epoch: 1200 | loss: 0.17194 - acc: 0.9713 -- iter: 1792/1811
Training Step: 18000  | total loss: 0.15989 | time: 29.034s
| Adam | epoch: 1200 | loss: 0.15989 - acc: 0.9726 -- iter: 1811/1811
--


In [55]:
y_pred = model_lstm.predict(X_train)

In [56]:
np.sum(np.argmax(y_train, axis=1)==np.argmax(y_pred, axis=1))/len(y_train)

0.8260629486471562

In [57]:
y_pred = model_lstm.predict(X_test)

In [58]:
np.sum(np.argmax(y_test, axis=1)==np.argmax(y_pred, axis=1))/len(y_test)

0.7320627802690582

In [59]:
model_lstm.save('model_gauss_mfccs_lstm.tflearn')

INFO:tensorflow:C:\Users\karti\Speech\LibriSpeech\dev-clean\model_gauss_mfccs_lstm.tflearn is not in all_model_checkpoint_paths. Manually adding it.
